### ISSUE TITLE
The term Abstract has no translation defined

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#82] opened 2022-09-16 21:58 UTC
What is this error? It is spammed on every invocation:
```sh
[WARNING] Could not load translations for en-US
  data file translations/en.yaml not found
WARNING:pypandoc:Could not load translations for en-US
  data file translations/en.yaml not found
[WARNING] The term Abstract has no translation defined.

WARNING:pypandoc:The term Abstract has no translation defined.
```

**Comment by novoid** [comment] 2022-09-18 14:37
Hi xeruf,

First: I don't get that warning on my machine. To my understanding, this is definitely nothing related to lazyblorg. I assume it is a pandoc-internal warning.

I could not find anything related to the message using my search engine of choice.

However, I can give you this analysis of my setup:

```
vk@sting ~ % locate "en.yaml"
/usr/share/pandoc/data/translations/en.yaml
vk@sting ~ % cd /usr/share/pandoc/data/translations/
vk@sting /usr/share/pandoc/data/translations % l
total 192
drwxr-xr-x 2 root root 4096 Nov  7  2021 ./
drwxr-xr-x 8 root root 4096 Nov  7  2021 ../
-rw-r--r-- 1 root root  519 Feb  8  2020 am.yaml
-rw-r--r-- 1 root root  557 Feb  8  2020 ar.yaml
-rw-r--r-- 1 root root  519 Feb  8  2020 bg.yaml
-rw-r--r-- 1 root root  759 Feb  8  2020 bn.yaml
-rw-r--r-- 1 root root  386 Feb  8  2020 ca.yaml
-rw-r--r-- 1 root root  367 Feb  8  2020 cs.yaml
-rw-r--r-- 1 root root  338 Feb  8  2020 da.yaml
-rw-r--r-- 1 root root  403 Feb  8  2020 de.yaml
-rw-r--r-- 1 root root  576 Feb  8  2020 el.yaml
-rw-r--r-- 1 root root  361 Feb  8  2020 en.yaml
-rw-r--r-- 1 root root  352 Feb  8  2020 eo.yaml
-rw-r--r-- 1 root root  407 Feb  8  2020 es.yaml
-rw-r--r-- 1 root root  336 Feb  8  2020 et.yaml
-rw-r--r-- 1 root root  410 Feb  8  2020 eu.yaml
-rw-r--r-- 1 root root  560 Feb  8  2020 fa.yaml
-rw-r--r-- 1 root root  361 Feb  8  2020 fi.yaml
-rw-r--r-- 1 root root  374 Feb  8  2020 fr.yaml
-rw-r--r-- 1 root root  469 Feb  8  2020 he.yaml
-rw-r--r-- 1 root root  559 Feb  8  2020 hi.yaml
-rw-r--r-- 1 root root  375 Feb  8  2020 hr.yaml
-rw-r--r-- 1 root root  437 Feb  8  2020 hu.yaml
-rw-r--r-- 1 root root  379 Feb  8  2020 is.yaml
-rw-r--r-- 1 root root  414 Feb  8  2020 it.yaml
-rw-r--r-- 1 root root  683 Feb  8  2020 km.yaml
-rw-r--r-- 1 root root  298 Feb  8  2020 ko.yaml
-rw-r--r-- 1 root root  713 Feb  8  2020 lo.yaml
-rw-r--r-- 1 root root  399 Feb  8  2020 lt.yaml
-rw-r--r-- 1 root root  356 Feb  8  2020 lv.yaml
-rw-r--r-- 1 root root  392 Feb  8  2020 nl.yaml
-rw-r--r-- 1 root root  346 Feb  8  2020 no.yaml
-rw-r--r-- 1 root root  381 Feb  8  2020 pl.yaml
-rw-r--r-- 1 root root  391 Feb  8  2020 pt.yaml
-rw-r--r-- 1 root root  428 Feb  8  2020 rm.yaml
-rw-r--r-- 1 root root  382 Feb  8  2020 ro.yaml
-rw-r--r-- 1 root root  579 Feb  8  2020 ru.yaml
-rw-r--r-- 1 root root  363 Feb  8  2020 sk.yaml
-rw-r--r-- 1 root root  348 Feb  8  2020 sl.yaml
-rw-r--r-- 1 root root  340 Feb  8  2020 sq.yaml
-rw-r--r-- 1 root root  540 Feb  8  2020 sr-cyrl.yaml
-rw-r--r-- 1 root root  379 Feb  8  2020 sr.yaml
-rw-r--r-- 1 root root  373 Feb  8  2020 sv.yaml
-rw-r--r-- 1 root root  642 Feb  8  2020 th.yaml
-rw-r--r-- 1 root root  390 Feb  8  2020 tr.yaml
-rw-r--r-- 1 root root  611 Feb  8  2020 uk.yaml
-rw-r--r-- 1 root root  563 Feb  8  2020 ur.yaml
-rw-r--r-- 1 root root  435 Feb  8  2020 vi.yaml
vk@sting /usr/share/pandoc/data/translations % dpkg -S /usr/share/pandoc/data/translations/en.yaml
pandoc-data: /usr/share/pandoc/data/translations/en.yaml
vk@sting /usr/share/pandoc/data/translations % 
```

According to this, I suggest to check if you got the package "pandoc-data" installed. Maybe this fixes the warning of your setup. If not, we'd have to compare pandoc settings although I can't remember changing them from their defaults. I'm running a Xubuntu LTS 22.04 here. 

Since it is not reproducible here and not related to lazyblorg, I'll close the issue for now. If you can find the pandoc fix, I'd love to read a comment of yours so that others are able to find the solution of yours for reference here.

Thank you!

**Closed by novoid** 2022-09-18 14:37 UTC
Labels: documentation

**Comment by xeruf** [comment] 2022-09-18 21:51
The file is there with a translation for "Abstract" as part of the `pandoc` package on Arch. So apparently pandoc is confused here ^^

I can reproduce it with the `pypandoc_test.py`, so let's see...
