### ISSUE TITLE
Missing simple markup like italics?

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#79] opened 2022-09-03 21:39 UTC
I have some italicized text which I can see being parsed in the log, but it stays wrapped in slashes and unformatted :/
```sh
DEBUG    2022-09-03 23:34:12,919 OrgParser: entry_content ###### line: "/That/ is why I don't want to eat as much meat,"
```

**Comment by novoid** [comment] 2022-09-07 20:25
This is a duplicate of https://github.com/novoid/lazyblorg/issues/25

**Closed by novoid** 2022-09-07 20:25 UTC
Labels: enhancement
